---
cloud_service_group: Database
cloud_service_type: CloudDB
name: Total Used Storage Size
query:
  aggregate:
    - group:
        fields:
          - name: Used Storage Size
            key: data.cloud_db_server_instance_list.used_data_storage
            operator: sum
options:
  value_options:
    key: Used Storage Size
    type: size
    options:
      default: 0
      source_unit: GB